### ISSUE TITLE
Classpath Issue with org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603, NoClassDefFoundError

### ISSUE THREAD

**Issue by philnate** [gwt-maven-plugin/gwt-maven-plugin#117]
It looks like the current snapshot is missing some dependency causing an NoClassDefFoundError during execution:

```
05:19:43 [INFO] --- gwt-maven-plugin:2.8.0.20150603:clean (default-cli) @ core ---
05:19:43 [DEBUG] Using mirror myMirror (http://myrepo.com/content/groups/public) for central (http://repo.maven.apache.org/maven2).
05:19:43 [DEBUG] org.codehaus.mojo:gwt-maven-plugin:jar:2.8.0.20150603:
05:19:43 [DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.1:runtime
05:19:43 [DEBUG] Created new class realm plugin>org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603
05:19:43 [DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603
05:19:43 [DEBUG]   Imported:  < maven.api
05:19:43 [DEBUG] Populating class realm plugin>org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603
05:19:43 [DEBUG]   Included: org.codehaus.mojo:gwt-maven-plugin:jar:2.8.0.20150603
05:19:43 [DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.1
05:19:43 [DEBUG] Configuring mojo org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603:clean from plugin realm ClassRealm[plugin>org.codehaus.mojo:gwt-maven-plugin:2.8.0.20150603, parent: sun.misc.Launcher$AppClassLoader@65fe28a7]
05:19:43 [WARNING] Error injecting: org.codehaus.mojo.gwt.GwtCleanMojo
05:19:43 java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/XmlStreamReader
05:19:43 	at java.lang.Class.getDeclaredConstructors0(Native Method)
05:19:43 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2483)
05:19:43 	at java.lang.Class.getDeclaredConstructors(Class.java:1891)
05:19:43 	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
05:19:43 	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:98)
05:19:43 	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
05:19:43 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:831)
05:19:43 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:758)
05:19:43 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:255)
05:19:43 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:204)
05:19:43 	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:954)
05:19:43 	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:987)
05:19:43 	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
05:19:43 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
05:19:43 	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
05:19:43 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
05:19:43 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
05:19:43 	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
05:19:43 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
05:19:43 	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
05:19:43 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
05:19:43 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
05:19:43 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
05:19:43 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
05:19:43 	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
05:19:43 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
05:19:43 	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
05:19:43 	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
05:19:43 	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
05:19:43 	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
05:19:43 	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
05:19:43 	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
05:19:43 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
05:19:43 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
05:19:43 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
05:19:43 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
05:19:43 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
05:19:43 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
05:19:43 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
05:19:43 	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
05:19:43 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
05:19:43 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
05:19:43 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
05:19:43 	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)
05:19:43 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:19:43 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
05:19:43 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:19:43 	at java.lang.reflect.Method.invoke(Method.java:606)
05:19:43 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
05:19:43 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
05:19:43 	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:178)
05:19:43 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:19:43 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
05:19:43 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:19:43 	at java.lang.reflect.Method.invoke(Method.java:606)
05:19:43 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
05:19:43 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
05:19:43 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
05:19:43 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
05:19:43 	at hudson.remoting.Request$2.run(Request.java:324)
05:19:43 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
05:19:43 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
05:19:43 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
05:19:43 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
05:19:43 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
05:19:43 	at java.lang.Thread.run(Thread.java:724)
05:19:43 Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.xml.XmlStreamReader
05:19:43 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
05:19:43 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
05:19:43 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
05:19:43 	... 66 more
05:19:43 [JENKINS] Archiving disabled
05:19:43 [INFO]                                                                         
05:19:43 [INFO] ------------------------------------------------------------------------
05:19:43 [INFO] Skipping Core
05:19:43 [INFO] This project has been banned from the build due to previous failures.
05:19:43 [INFO] ------------------------------------------------------------------------
05:19:43 [INFO] 
```

**Comment by romixch** [comment]
I have the same issue now. Some hours ago, everything worked fine. Now mvn gwt:run always fails with this message. No matter which commit I checkout. How did you solve the problem?

**Comment by ibaca** [comment]
Can not reproduce.
