### ISSUE TITLE
Pass gwt.jjs.permutationWorkerFactory property

### ISSUE THREAD

**Issue by kenjiuno** [gwt-maven-plugin/gwt-maven-plugin#149]
I have a problem to build jbpm-designer-standalone on `gwt:compile` goal.

My command:
```
mvn -Dfull -DskipTests -Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory -DforkMode=never gwt:compile
```

Output:
```
C:\Git\jbpm-designer\jbpm-designer-standalone>mvn -Dfull -DskipTests -Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory -DforkMode=never gwt:compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jBPM Designer - Standalone 7.0.0.Beta6
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.wildfly.core:wildfly-cli:jar:2.1.0.Final is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.wildfly.core:wildfly-embedded:jar:2.1.0.Final is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- gwt-maven-plugin:2.8.0:compile (default-cli) @ jbpm-designer-standalone ---
[ERROR] 2 28, 2017 6:02:41 午後 java.util.prefs.WindowsPreferences <init>
[ERROR] 警告: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[INFO] Compiling module org.jbpm.designer.jBPMDesigner
...
[INFO]    Compiling 2 permutations
[INFO]       [ERROR] Unable to start external process
[INFO] java.io.IOException: Cannot run program "C:\Java8\jre\bin\java": CreateProcess error=206, ファイル名または拡張子が長すぎます。
[INFO]  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[INFO]  at com.google.gwt.dev.ExternalPermutationWorkerFactory.launchExternalWorker(ExternalPermutationWorkerFactory.java:282)
[INFO]  at com.google.gwt.dev.ExternalPermutationWorkerFactory.getWorkers(ExternalPermutationWorkerFactory.java:374)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory.createWorkers(PermutationWorkerFactory.java:351)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory.compilePermutations(PermutationWorkerFactory.java:254)
[INFO]  at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:211)
[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:219)
[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO]  at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO]  at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO]  at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO]  at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.io.IOException: CreateProcess error=206, ファイル名または拡張子が長すぎます。
[INFO]  at java.lang.ProcessImpl.create(Native Method)
[INFO]  at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[INFO]  at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[INFO]  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[INFO]  ... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:34 min
[INFO] Finished at: 2017-02-28T18:05:22+09:00
[INFO] Final Memory: 142M/1528M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0:compile (default-cli) on project jbpm-designer-standalone: Command failed with status 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The problem is that command line is too long due to probably long long CLASSPATH (may relates to #113 ?).
`[INFO] java.io.IOException: Cannot run program "C:\Java8\jre\bin\java": CreateProcess error=206, ファイル名または拡張子が長すぎます。
`

I have found that another java is launched for gwt compiler: https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/gwt-maven-plugin-2.8.0/src/main/java/org/codehaus/mojo/gwt/shell/CompileMojo.java#L409

Someone says `-Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory` helps to avoid the classpath problem of gwt compiler side.

Can I pass `gwt.jjs.permutationWorkerFactory` to the another Java instance for gwt compiler?

**Comment by kenjiuno** [comment]
Thanks, problem solved: `<extraJvmArgs>` in pom.xml helped.

```xml
          <plugin><!-- Keep in sync with soa profile -->
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>gwt-maven-plugin</artifactId>
            <configuration>
              <!-- Build all GWT permutations and optimize them -->
              <module>org.jbpm.designer.jBPMDesigner</module>
              <draftCompile>false</draftCompile>
              <extraJvmArgs>-Xms1g -Xmx2g -Xss1M -Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory</extraJvmArgs>
            </configuration>
          </plugin>
```

```
[INFO]    Compiling 2 permutations
[INFO]       Compiling permutation 0...
[INFO]       Compiling permutation 1...
[INFO]    Compile of permutations succeeded
[INFO]    Compilation succeeded -- 277.841s
[INFO] Linking into C:\Git\jbpm-designer\jbpm-designer-standalone\target\jbpm-designer-standalone\org.jbpm.designer.jBPMDesig
[INFO]    Link succeeded
[INFO]    Linking succeeded -- 24.173s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:37 min
[INFO] Finished at: 2017-03-01T09:22:23+09:00
[INFO] Final Memory: 178M/1363M
[INFO] ------------------------------------------------------------------------
```
